### ISSUE TITLE
Compile Error on Android

### ISSUE THREAD

**Issue by wayne1203** [jsierles/react-native-audio#198]
### Tell us which versions you are using ( you can see the versions in your package.json ):

react-native-audio :  3.2.2
react-native : Installed today with react-native init
react :  Installed today with react-native init
using react-native-sound ? Yes

### Expected behaviour :

What were you trying to do and what did you expect to happen ?

It's fine in "react-native run-ios" but
tried to run "react-native run-android" and got

```
ReactNativeAudioPackage.java:35: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-audio:compileReleaseJavaWithJavac FAILED
```

**Comment by wayne1203** [comment]
OK, I found the solution on "Issue" in other Github problem
[](https://github.com/ivpusic/react-native-image-crop-picker/issues/404)

In react-native v0.47.1, ReactPackage interface does not have "createJSModules" method for override.
Just comment "Override" in
/node_modules/react-native-audio/android/src/main/java/com/rnim/rn/audio/ReactNativeAudioPackage.java:35

**Comment by paldepind** [comment]
I'm getting this error as well. Commenting the override does work. As far as I can tell this issue should not be closed. The latest release does not work with the latest React Native.

**Comment by Damnum** [comment]
Is it documented anywhere that this library does not work with RN 0.47? Commenting the override is not a permanent solution
