### PR TITLE
Handle Android RN 0.47 breaking change

### LINKED ISSUE #198: Compile Error on Android
### Tell us which versions you are using ( you can see the versions in your package.json ):

react-native-audio :  3.2.2
react-native : Installed today with react-native init
react :  Installed today with react-native init
using react-native-sound ? Yes

### Expected behaviour :

What were you trying to do and what did you expect to happen ?

It's fine in "react-native run-ios" but
tried to run "react-native run-android" and got

```
ReactNativeAudioPackage.java:35: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-audio:compileReleaseJavaWithJavac FAILED
```

### PR DESCRIPTION
**Pull request by paldepind**
Fixes  #198 and makes react-native-audio work with React Native 0.47.

### CODE REVIEW

**Comment by paldepind** [comment]
It would probably be a good idea to release this on npm as soon as possible. The current version doesn't compile with 0.47.

**Comment by RakanNimer** [comment]
Hey !

Thanks for the PR, can you please also bump the version in package.json to 3.3.0.

Also leaving a note here that we need to update the README before publishing to NPM to clarify that people using RN versions < 0.47 need to stick to 3.2.*

**Comment by paldepind** [comment]
@RakanNimer Is this not backward compatible? I'm not very experienced with Java, but the `createJSModules` method is still there. It's just not annotated as overriding anymore. So I think it's backward compatible.

**Comment by rohitgoyal** [comment]
I am also getting this. 

> node_modules/react-native-audio/android/src/main/java/com/rnim/rn/audio/ReactNativeAudioPackage.java:35: error: method does not override or implement a method from a supertype
>     @Override
>     ^
> 1 error
> :react-native-audio:compileReleaseJavaWithJavac FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':react-native-audio:compileReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.

When is it supposed to resolve in master branch?

**Comment by Commander-lol** [comment]
Removing the `@Override` annotation is backwards compatible - it was added in Java 1.5 as a compiler hint to protect against mistyping a method name when overriding classes, but is entirely optional. 

For that same reason, i'd also throw my vote in for this PR or over #205 because it wouldn't prevent features & fixes from reaching people using RN < 0.47

**Comment by brunsy** [comment]
PR #199 already contains this fix, so this can be closed...
